INSERT INTO tools (name, slug, description, logo_url, category, views_count, votes_count) VALUES
('ChatGPT', 'chatgpt', 'Conversational AI assistant by OpenAI for natural language tasks', 'https://logo.clearbit.com/openai.com', 'Writing', 15420, 2847),
('Claude', 'claude', 'Advanced AI assistant by Anthropic for complex reasoning and analysis', 'https://logo.clearbit.com/anthropic.com', 'Writing', 12350, 2156),
('Midjourney', 'midjourney', 'AI art generator creating stunning images from text descriptions', 'https://logo.clearbit.com/midjourney.com', 'Image Generation', 18920, 3421),
('DALL-E 3', 'dall-e-3', 'OpenAI image generation model with photorealistic capabilities', 'https://logo.clearbit.com/openai.com', 'Image Generation', 14230, 2634),
('Stable Diffusion', 'stable-diffusion', 'Open-source image generation model for creative artwork', 'https://logo.clearbit.com/stability.ai', 'Image Generation', 11540, 2089),
('GitHub Copilot', 'github-copilot', 'AI pair programmer that suggests code completions in real-time', 'https://logo.clearbit.com/github.com', 'Code', 16780, 3124),
('Cursor', 'cursor', 'AI-powered code editor built for productivity and collaboration', 'https://logo.clearbit.com/cursor.sh', 'Code', 9870, 1876),
('Notion AI', 'notion-ai', 'AI writing assistant integrated into Notion workspace', 'https://logo.clearbit.com/notion.so', 'Productivity', 13450, 2456),
('Grammarly', 'grammarly', 'AI writing assistant for grammar, spelling, and style improvements', 'https://logo.clearbit.com/grammarly.com', 'Writing', 19340, 3567),
('Jasper', 'jasper', 'AI content creation platform for marketing and business writing', 'https://logo.clearbit.com/jasper.ai', 'Writing', 8920, 1654),
('Copy.ai', 'copy-ai', 'AI copywriting tool for marketing content and social media', 'https://logo.clearbit.com/copy.ai', 'Writing', 7650, 1423),
('Runway', 'runway', 'AI video editing and generation platform for creators', 'https://logo.clearbit.com/runwayml.com', 'Video', 10230, 1987),
('Synthesia', 'synthesia', 'AI video generation with realistic avatars and voiceovers', 'https://logo.clearbit.com/synthesia.io', 'Video', 6780, 1234),
('Descript', 'descript', 'AI-powered audio and video editing with transcription', 'https://logo.clearbit.com/descript.com', 'Video', 8450, 1567),
('ElevenLabs', 'elevenlabs', 'AI voice generation and cloning with natural speech synthesis', 'https://logo.clearbit.com/elevenlabs.io', 'Audio', 11230, 2145),
('Murf AI', 'murf-ai', 'AI voiceover generator for professional audio content', 'https://logo.clearbit.com/murf.ai', 'Audio', 5670, 987),
('Perplexity', 'perplexity', 'AI-powered search engine with cited sources and answers', 'https://logo.clearbit.com/perplexity.ai', 'Research', 12890, 2378),
('Consensus', 'consensus', 'AI research assistant that searches scientific papers', 'https://logo.clearbit.com/consensus.app', 'Research', 4560, 876),
('Elicit', 'elicit', 'AI research assistant for literature reviews and analysis', 'https://logo.clearbit.com/elicit.org', 'Research', 3890, 734),
('Otter.ai', 'otter-ai', 'AI meeting transcription and note-taking assistant', 'https://logo.clearbit.com/otter.ai', 'Productivity', 9340, 1765),
('Fireflies.ai', 'fireflies-ai', 'AI meeting recorder and transcription service', 'https://logo.clearbit.com/fireflies.ai', 'Productivity', 7230, 1345),
('Tome', 'tome', 'AI-powered presentation and storytelling platform', 'https://logo.clearbit.com/tome.app', 'Productivity', 6120, 1123),
('Beautiful.ai', 'beautiful-ai', 'AI presentation software with smart templates', 'https://logo.clearbit.com/beautiful.ai', 'Productivity', 5450, 998),
('Canva AI', 'canva-ai', 'AI-powered design platform for graphics and presentations', 'https://logo.clearbit.com/canva.com', 'Image Generation', 17650, 3289),
('Adobe Firefly', 'adobe-firefly', 'Adobe generative AI for creative design and images', 'https://logo.clearbit.com/adobe.com', 'Image Generation', 10890, 2012),
('Lensa AI', 'lensa-ai', 'AI photo editor and avatar generator', 'https://logo.clearbit.com/prisma-ai.com', 'Image Generation', 8760, 1623),
('Replit Ghostwriter', 'replit-ghostwriter', 'AI coding assistant integrated into Replit IDE', 'https://logo.clearbit.com/replit.com', 'Code', 7890, 1456),
('Tabnine', 'tabnine', 'AI code completion tool for multiple programming languages', 'https://logo.clearbit.com/tabnine.com', 'Code', 6540, 1234),
('Codeium', 'codeium', 'Free AI code completion and chat assistant', 'https://logo.clearbit.com/codeium.com', 'Code', 5670, 1087),
('Phind', 'phind', 'AI search engine optimized for developers and technical queries', 'https://logo.clearbit.com/phind.com', 'Research', 6780, 1289),
('Writesonic', 'writesonic', 'AI writing assistant for articles, ads, and content', 'https://logo.clearbit.com/writesonic.com', 'Writing', 5890, 1098),
('Rytr', 'rytr', 'AI writing assistant for various content types', 'https://logo.clearbit.com/rytr.me', 'Writing', 4560, 876),
('QuillBot', 'quillbot', 'AI paraphrasing and grammar checking tool', 'https://logo.clearbit.com/quillbot.com', 'Writing', 11230, 2087),
('Wordtune', 'wordtune', 'AI writing companion for rewriting and suggestions', 'https://logo.clearbit.com/wordtune.com', 'Writing', 6890, 1276),
('Pictory', 'pictory', 'AI video creation from text and articles', 'https://logo.clearbit.com/pictory.ai', 'Video', 5670, 1045),
('HeyGen', 'heygen', 'AI video generation with customizable avatars', 'https://logo.clearbit.com/heygen.com', 'Video', 7230, 1356),
('Fliki', 'fliki', 'AI text-to-video and voiceover platform', 'https://logo.clearbit.com/fliki.ai', 'Video', 4890, 912),
('Soundraw', 'soundraw', 'AI music generation for content creators', 'https://logo.clearbit.com/soundraw.io', 'Audio', 5120, 967),
('AIVA', 'aiva', 'AI music composition for soundtracks and scores', 'https://logo.clearbit.com/aiva.ai', 'Audio', 4560, 845),
('Boomy', 'boomy', 'AI music creation platform for instant songs', 'https://logo.clearbit.com/boomy.com', 'Audio', 3890, 723),
('Krisp', 'krisp', 'AI noise cancellation for calls and recordings', 'https://logo.clearbit.com/krisp.ai', 'Audio', 6780, 1267),
('Cleanvoice', 'cleanvoice', 'AI audio editing to remove filler words and noise', 'https://logo.clearbit.com/cleanvoice.ai', 'Audio', 3450, 645),
('Podcastle', 'podcastle', 'AI podcast recording and editing platform', 'https://logo.clearbit.com/podcastle.ai', 'Audio', 4230, 789),
('Lexica', 'lexica', 'AI art search engine and image generation', 'https://logo.clearbit.com/lexica.art', 'Image Generation', 7890, 1456),
('Leonardo.ai', 'leonardo-ai', 'AI image generation for game assets and creative work', 'https://logo.clearbit.com/leonardo.ai', 'Image Generation', 6540, 1223),
('Playground AI', 'playground-ai', 'AI image creation and editing playground', 'https://logo.clearbit.com/playgroundai.com', 'Image Generation', 5670, 1067),
('Remove.bg', 'remove-bg', 'AI background removal for images', 'https://logo.clearbit.com/remove.bg', 'Image Generation', 12340, 2289),
('Cleanup.pictures', 'cleanup-pictures', 'AI object removal and image cleanup', 'https://logo.clearbit.com/cleanup.pictures', 'Image Generation', 6780, 1256),
('Upscale.media', 'upscale-media', 'AI image upscaling and enhancement', 'https://logo.clearbit.com/upscale.media', 'Image Generation', 5890, 1089),
('Looka', 'looka', 'AI logo and brand identity generator', 'https://logo.clearbit.com/looka.com', 'Image Generation', 7230, 1345),
('Designs.ai', 'designs-ai', 'AI design suite for logos, videos, and mockups', 'https://logo.clearbit.com/designs.ai', 'Image Generation', 4560, 856),
('Gamma', 'gamma', 'AI presentation and document creation platform', 'https://logo.clearbit.com/gamma.app', 'Productivity', 8120, 1523),
('Motion', 'motion', 'AI calendar and task management for productivity', 'https://logo.clearbit.com/usemotion.com', 'Productivity', 6890, 1289),
('Reclaim.ai', 'reclaim-ai', 'AI calendar assistant for time management', 'https://logo.clearbit.com/reclaim.ai', 'Productivity', 5670, 1056),
('Mem', 'mem', 'AI-powered note-taking and knowledge management', 'https://logo.clearbit.com/mem.ai', 'Productivity', 4890, 912),
('Superhuman', 'superhuman', 'AI-enhanced email client for productivity', 'https://logo.clearbit.com/superhuman.com', 'Productivity', 9340, 1745);
